"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
from setuptools import setup

APP = ['./src/main.py']
APP_NAME = "PomoLocker"
DATA_FILES = []

OPTIONS = {
    'excludes': ['setuptools', 'macholib', 'modulegraph'],
    'argv_emulation': False,
    'iconfile': 'appicon.icns',
    'plist': { # Optional: Add macOS specific metadata
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "A simple centered Tkinter application",
        'CFBundleIdentifier': "com.yourdomain.centeredapp", # Replace with your own identifier
        'CFBundleVersion': "0.1.0",
        'CFBundleShortVersionString': "0.1.0",
        'NSHumanReadableCopyright': u"Copyright © 2025, Your Name or Company" # Update copyright
    }
}

setup(
    app=APP,
    name=APP_NAME,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)